/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#define BUILDING_LIBRARY
#include "lib_iopins.h"
#include <avr/io.h>
// ----------- Define the used ports ------------
static const IOPort PROGMEM _PORTB={_SFR_MEM_ADDR(PORTB),_SFR_MEM_ADDR(DDRB),_SFR_MEM_ADDR(PINB)};
static const IOPort PROGMEM _PORTC={_SFR_MEM_ADDR(PORTC),_SFR_MEM_ADDR(DDRC),_SFR_MEM_ADDR(PINC)};
static const IOPort PROGMEM _PORTD={_SFR_MEM_ADDR(PORTD),_SFR_MEM_ADDR(DDRD),_SFR_MEM_ADDR(PIND)};
static const IOPort PROGMEM _PORTE={_SFR_MEM_ADDR(PORTE),_SFR_MEM_ADDR(DDRE),_SFR_MEM_ADDR(PINE)};
static const IOPort PROGMEM _PORTG={_SFR_MEM_ADDR(PORTG),_SFR_MEM_ADDR(DDRG),_SFR_MEM_ADDR(PING)};
static const IOPort PROGMEM _PORTH={_SFR_MEM_ADDR(PORTH),_SFR_MEM_ADDR(DDRH),_SFR_MEM_ADDR(PINH)};
static const IOPort PROGMEM _PORTL={_SFR_MEM_ADDR(PORTL),_SFR_MEM_ADDR(DDRL),_SFR_MEM_ADDR(PINL)};

// ----------- Define the used pins ------------
const IOPin PROGMEM _B4 = { &_PORTB, BV(4)};
const IOPin PROGMEM _B5 = { &_PORTB, BV(5)};
const IOPin PROGMEM _B6 = { &_PORTB, BV(6)};
const IOPin PROGMEM _B7 = { &_PORTB, BV(7)};
const IOPin PROGMEM _C0 = { &_PORTC, BV(0)};
const IOPin PROGMEM _C1 = { &_PORTC, BV(1)};
const IOPin PROGMEM _C2 = { &_PORTC, BV(2)};
const IOPin PROGMEM _C3 = { &_PORTC, BV(3)};
const IOPin PROGMEM _C4 = { &_PORTC, BV(4)};
const IOPin PROGMEM _C5 = { &_PORTC, BV(5)};
const IOPin PROGMEM _D2 = { &_PORTD, BV(2)};
const IOPin PROGMEM _D3 = { &_PORTD, BV(3)};
const IOPin PROGMEM _D5 = { &_PORTD, BV(5)};
const IOPin PROGMEM _D6 = { &_PORTD, BV(6)};
const IOPin PROGMEM _D7 = { &_PORTD, BV(7)};
const IOPin PROGMEM _E3 = { &_PORTE, BV(3)};
const IOPin PROGMEM _E4 = { &_PORTE, BV(4)};
const IOPin PROGMEM _E5 = { &_PORTE, BV(5)};
const IOPin PROGMEM _E7 = { &_PORTE, BV(7)};
const IOPin PROGMEM _G5 = { &_PORTG, BV(5)};
const IOPin PROGMEM _H3 = { &_PORTH, BV(3)};
const IOPin PROGMEM _H4 = { &_PORTH, BV(4)};
const IOPin PROGMEM _H5 = { &_PORTH, BV(5)};
const IOPin PROGMEM _H6 = { &_PORTH, BV(6)};
const IOPin PROGMEM _L0 = { &_PORTL, BV(0)};
const IOPin PROGMEM _L1 = { &_PORTL, BV(1)};
const IOPin PROGMEM _L3 = { &_PORTL, BV(3)};
const IOPin PROGMEM _L4 = { &_PORTL, BV(4)};
const IOPin PROGMEM _L5 = { &_PORTL, BV(5)};
const uint16_t PROGMEM AVcc_MV = 5000;
