/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef _LIB_HARDWARE_C_
#define _LIB_HARDWARE_C_
#include "../hardware.h"

// ------------------- uart1 -------------------

// Make a transmit buffer for uart1
static unsigned char tx_uart1_Buf[500];
static cBuffer tx_uart1_Buffer = MAKE_BUFFER(tx_uart1_Buf);

// Make a receive buffer for uart1
static unsigned char rx_uart1_Buf[500];
static cBuffer rx_uart1_Buffer = MAKE_BUFFER(rx_uart1_Buf);


// Create a routine to write bytes to uart1
// You can set rprintf to use it by calling rprintfInit(&uart1SendByte)
MAKE_WRITER(uart1SendByte){
	return uartSendByte(_C_uart1,byte);
}

// Create a routine to read a byte from uart1
// Returns -1 if there was no data
MAKE_READER( uart1GetByte){
	return uartGetByte(_C_uart1);
}

// Create hardware UART _C_uart1
HW_UART __C_uart1 = MAKE_HW_UART_Rx_Tx(&rx_uart1_Buffer,&tx_uart1_Buffer,UCSR1A,UCSR1B,UBRR1L,UBRR1H,UDR1,null,BV(U2X1),D2,D3,&uart1GetByte,&uart1SendByte);

#ifndef USART1_TX_vect
# error Uart1 Tx complete vector undefined
#else
ISR(USART1_TX_vect){
	uartTransmitService(_C_uart1);
}
#endif

#ifndef USART1_RX_vect
# error Uart1 Rx complete vector undefined
#else
ISR(USART1_RX_vect){
	uartReceiveService(_C_uart1);
}
#endif

// ----------- Define the ADC channels ----------
const uint8_t NUM_ADC_CHANNELS = 16;

// ----------- My devices -----------------------
SWITCH _button_ = MAKE_SWITCH(D5);
SEGLED _led_display_ = MAKE_SEGLED(C3,C2,C0,D6,D7,C4,C5,null,false);
static const SEGLED_LIST PROGMEM marquee_list[] = {
	&_led_display_
};
static MAKE_WRITER(marquee_put_char); /* Fwd Def */
MARQUEE _marquee_ = MAKE_MARQUEE(marquee_list,500000,2000000,&marquee_put_char);
// Create a Writer to write to marquee
// Do NOT call it directly instead, to write the char 'A' use:
// 	marqueeGetWriter(&marquee)('A');
static MAKE_WRITER(marquee_put_char){ /* createWriter */
	return marqueeSendByte(&_marquee_,byte);
}
SERVO _servo_ = MAKE_SERVO(false,B5,1500,1000);
SERVO _servo2_ = MAKE_SERVO(false,B6,1500,1000);
SERVO _servo3_ = MAKE_SERVO(false,B7,1500,1000);
SERVO _servo4_ = MAKE_SERVO(false,E3,1500,1000);
SERVO _servo5_ = MAKE_SERVO(false,E4,1500,1000);
SERVO _servo6_ = MAKE_SERVO(false,E5,1500,1000);
static const SERVO_LIST PROGMEM Servos1_list[] = {
	&_servo_,
	&_servo2_,
	&_servo3_,
	&_servo4_,
	&_servo5_,
	&_servo6_
};
SERVO_DRIVER _Servos1_ = MAKE_SERVO_DRIVER(Servos1_list);
SERVO _servo7_ = MAKE_SERVO(false,H3,1500,1000);
SERVO _servo8_ = MAKE_SERVO(false,H4,1500,1000);
SERVO _servo9_ = MAKE_SERVO(false,H5,1500,1000);
SERVO _servo10_ = MAKE_SERVO(false,L3,1500,1000);
SERVO _servo11_ = MAKE_SERVO(false,L4,1500,1000);
SERVO _servo12_ = MAKE_SERVO(false,L5,1500,1000);
static const SERVO_LIST PROGMEM servos2_list[] = {
	&_servo7_,
	&_servo8_,
	&_servo9_,
	&_servo10_,
	&_servo11_,
	&_servo12_
};
SERVO_DRIVER _servos2_ = MAKE_SERVO_DRIVER(servos2_list);

// ----------- Initialise built in devices ------
void sysInitHardware(void){
	SWITCH_init(&_button_);
	setErrorLog(&uart1SendByte);
	rprintfInit(&uart1SendByte);
	uartInit(_C_uart1,115200);
	segled_init(&_led_display_);
}

// ----------- Initialise my added devices ------
void initHardware(void){
	servoPWMInit(&_Servos1_);
	servoPWMInit(&_servos2_);
}
// ----------- Register the statusLED -----------
void registerLED(void){
	statusLEDregister(C1,false);
}

#endif
