/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef LIB_IOPINS_H
#define LIB_IOPINS_H
#include <libdefs.h>
#ifdef __cplusplus
extern "C" {
#endif

// ----------- Define the used pins ------------
extern const IOPin PROGMEM _B4;
extern const IOPin PROGMEM _B5;
extern const IOPin PROGMEM _B6;
extern const IOPin PROGMEM _B7;
extern const IOPin PROGMEM _C0;
extern const IOPin PROGMEM _C1;
extern const IOPin PROGMEM _C2;
extern const IOPin PROGMEM _C3;
extern const IOPin PROGMEM _C4;
extern const IOPin PROGMEM _C5;
extern const IOPin PROGMEM _D2;
extern const IOPin PROGMEM _D3;
extern const IOPin PROGMEM _D5;
extern const IOPin PROGMEM _D6;
extern const IOPin PROGMEM _D7;
extern const IOPin PROGMEM _E3;
extern const IOPin PROGMEM _E4;
extern const IOPin PROGMEM _E5;
extern const IOPin PROGMEM _E7;
extern const IOPin PROGMEM _G5;
extern const IOPin PROGMEM _H3;
extern const IOPin PROGMEM _H4;
extern const IOPin PROGMEM _H5;
extern const IOPin PROGMEM _H6;
extern const IOPin PROGMEM _L0;
extern const IOPin PROGMEM _L1;
extern const IOPin PROGMEM _L3;
extern const IOPin PROGMEM _L4;
extern const IOPin PROGMEM _L5;
#define B4 &_B4
#define B5 &_B5
#define B6 &_B6
#define B7 &_B7
#define C0 &_C0
#define C1 &_C1
#define C2 &_C2
#define C3 &_C3
#define C4 &_C4
#define C5 &_C5
#define D2 &_D2
#define D3 &_D3
#define D5 &_D5
#define D6 &_D6
#define D7 &_D7
#define E3 &_E3
#define E4 &_E4
#define E5 &_E5
#define E7 &_E7
#define G5 &_G5
#define H3 &_H3
#define H4 &_H4
#define H5 &_H5
#define H6 &_H6
#define L0 &_L0
#define L1 &_L1
#define L3 &_L3
#define L4 &_L4
#define L5 &_L5
#ifdef __cplusplus
}
#endif
#endif
