/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef _LIB_CTOR_H_
#define _LIB_CTOR_H_
extern StatusLed statusLed;
extern Switch button;
extern Marquee marquee;
extern Servo servo;
extern Servo servo2;
extern Servo servo3;
extern Servo servo4;
extern Servo servo5;
extern Servo servo6;
extern ServoDriver Servos1;
extern Servo servo7;
extern Servo servo8;
extern Servo servo9;
extern Servo servo10;
extern Servo servo11;
extern Servo servo12;
extern ServoDriver servos2;
extern UartHW uart1;
#endif
