/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef LIB_TIMERDEF_H
#define LIB_TIMERDEF_H
#include <libdefs.h>
#ifdef __cplusplus
extern "C" {
#endif
// ----------- Start Timer Definition -------------

// Define timer 0
extern const TimerCompare PROGMEM __timer0Compare[];
#define TIMER0_COMPAREA &__timer0Compare[0]
#define TIMER0_COMPAREB &__timer0Compare[1]

// Define timer 1
extern const TimerCompare PROGMEM __timer1Compare[];
#define TIMER1_COMPAREA &__timer1Compare[0]
#define TIMER1_COMPAREB &__timer1Compare[1]
#define TIMER1_COMPAREC &__timer1Compare[2]

// Define timer 2
extern const TimerCompare PROGMEM __timer2Compare[];
#define TIMER2_COMPAREA &__timer2Compare[0]
#define TIMER2_COMPAREB &__timer2Compare[1]

// Define timer 3
extern const TimerCompare PROGMEM __timer3Compare[];
#define TIMER3_COMPAREA &__timer3Compare[0]
#define TIMER3_COMPAREB &__timer3Compare[1]
#define TIMER3_COMPAREC &__timer3Compare[2]

// Define timer 4
extern const TimerCompare PROGMEM __timer4Compare[];
#define TIMER4_COMPAREA &__timer4Compare[0]
#define TIMER4_COMPAREB &__timer4Compare[1]
#define TIMER4_COMPAREC &__timer4Compare[2]

// Define timer 5
extern const TimerCompare PROGMEM __timer5Compare[];
#define TIMER5_COMPAREA &__timer5Compare[0]
#define TIMER5_COMPAREB &__timer5Compare[1]
#define TIMER5_COMPAREC &__timer5Compare[2]

// Create table of timers
extern const PROGMEM Timer PROGMEM pgm_Timers[];
extern const uint8_t NUMBER_OF_TIMERS;
#define TIMER0 &pgm_Timers[0]
#define TIMER1 &pgm_Timers[1]
#define TIMER2 &pgm_Timers[2]
#define TIMER3 &pgm_Timers[3]
#define TIMER4 &pgm_Timers[4]
#define TIMER5 &pgm_Timers[5]
// ----------- End Timer Definition -------------

#ifdef __cplusplus
}
#endif
#endif
