/*
		This file has been auto-generated by WebbotLib tools V2.1
				** DO NOT MODIFY BY HAND **
*/
#define BUILDING_LIBRARY
#include <avr/io.h>
#include <libdefs.h>
#include "lib_timerdef.h"
#include "lib_iopins.h"

// Type of interrupt handler to use for timer interrupts.
// Do not change unless you know what you're doing.
#ifndef TIMER_INTERRUPT_HANDLER
#define TIMER_INTERRUPT_HANDLER	ISR
#endif
// ----------- Start Timer Definition -------------

// Define timer 0
static TimerData __timer0_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer0CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer0CompareB_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer0Compare[] = {
	MAKE_TIMER_COMPARE(__timer0CompareA_data,0,TIMSK0,OCIE0A,OCR0A,TIFR0,OCF0A,TCCR0A,COM0A0,B7),
	MAKE_TIMER_COMPARE(__timer0CompareB_data,0,TIMSK0,OCIE0B,OCR0B,TIFR0,OCF0B,TCCR0A,COM0B0,G5)
};

// Define timer 1
static TimerData __timer1_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer1CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer1CompareB_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer1CompareC_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer1Compare[] = {
	MAKE_TIMER_COMPARE(__timer1CompareA_data,1,TIMSK1,OCIE1A,OCR1A,TIFR1,OCF1A,TCCR1A,COM1A0,B5),
	MAKE_TIMER_COMPARE(__timer1CompareB_data,1,TIMSK1,OCIE1B,OCR1B,TIFR1,OCF1B,TCCR1A,COM1B0,B6),
	MAKE_TIMER_COMPARE(__timer1CompareC_data,1,TIMSK1,OCIE1C,OCR1C,TIFR1,OCF1C,TCCR1A,COM1C0,B7)
};

// Define timer 2
static TimerData __timer2_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer2CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer2CompareB_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer2Compare[] = {
	MAKE_TIMER_COMPARE(__timer2CompareA_data,2,TIMSK2,OCIE2A,OCR2A,TIFR2,OCF2A,TCCR2A,COM2A0,B4),
	MAKE_TIMER_COMPARE(__timer2CompareB_data,2,TIMSK2,OCIE2B,OCR2B,TIFR2,OCF2B,TCCR2A,COM2B0,H6)
};

// Define timer 3
static TimerData __timer3_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer3CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer3CompareB_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer3CompareC_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer3Compare[] = {
	MAKE_TIMER_COMPARE(__timer3CompareA_data,3,TIMSK3,OCIE3A,OCR3A,TIFR3,OCF3A,TCCR3A,COM3A0,E3),
	MAKE_TIMER_COMPARE(__timer3CompareB_data,3,TIMSK3,OCIE3B,OCR3B,TIFR3,OCF3B,TCCR3A,COM3B0,E4),
	MAKE_TIMER_COMPARE(__timer3CompareC_data,3,TIMSK3,OCIE3C,OCR3C,TIFR3,OCF3C,TCCR3A,COM3C0,E5)
};

// Define timer 4
static TimerData __timer4_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer4CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer4CompareB_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer4CompareC_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer4Compare[] = {
	MAKE_TIMER_COMPARE(__timer4CompareA_data,4,TIMSK4,OCIE4A,OCR4A,TIFR4,OCF4A,TCCR4A,COM4A0,H3),
	MAKE_TIMER_COMPARE(__timer4CompareB_data,4,TIMSK4,OCIE4B,OCR4B,TIFR4,OCF4B,TCCR4A,COM4B0,H4),
	MAKE_TIMER_COMPARE(__timer4CompareC_data,4,TIMSK4,OCIE4C,OCR4C,TIFR4,OCF4C,TCCR4A,COM4C0,H5)
};

// Define timer 5
static TimerData __timer5_data = MAKE_TIMER_DATA(0);
static TimerDataCompare __timer5CompareA_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer5CompareB_data = MAKE_TIMER_COMPARE_DATA();
static TimerDataCompare __timer5CompareC_data = MAKE_TIMER_COMPARE_DATA();
const TimerCompare PROGMEM __timer5Compare[] = {
	MAKE_TIMER_COMPARE(__timer5CompareA_data,5,TIMSK5,OCIE5A,OCR5A,TIFR5,OCF5A,TCCR5A,COM5A0,L3),
	MAKE_TIMER_COMPARE(__timer5CompareB_data,5,TIMSK5,OCIE5B,OCR5B,TIFR5,OCF5B,TCCR5A,COM5B0,L4),
	MAKE_TIMER_COMPARE(__timer5CompareC_data,5,TIMSK5,OCIE5C,OCR5C,TIFR5,OCF5C,TCCR5A,COM5C0,L5)
};

// Create table of unique timer prescalers
static const uint16_t PROGMEM prescale_a[]={6/* bytes that follow */,0,1,8,64,256,1024};
static const uint16_t PROGMEM prescale_b[]={8/* bytes that follow */,0,1,8,32,64,128,256,1024};

// Create uinque tables of mode to wgm values
static const uint8_t PROGMEM mode2WGM_a[]={0,1,255,255,2,3,255,255,255,255,255,5,255,255,255,7};
static const uint8_t PROGMEM mode2WGM_b[]={0,1,2,3,4,5,6,7,8,9,10,11,12,255,14,15};

// Create table of timers
const PROGMEM Timer PROGMEM pgm_Timers[] = {
	MAKE_TIMER(__timer0_data,TCNT0,TCCR0B,7,false,16,mode2WGM_a,
		TCCR0A,WGM00,TCCR0A,WGM01,TCCR0B,WGM02,UNUSED_PORT,0,
		__timer0Compare,TIMSK0,TOIE0,TIFR0,TOV0,UNUSED_PORT,UNUSED_PORT,0,UNUSED_PORT,0,UNUSED_PORT,0,null,prescale_a),
	MAKE_TIMER(__timer1_data,TCNT1,TCCR1B,7,true,16,mode2WGM_b,
		TCCR1A,WGM10,TCCR1A,WGM11,TCCR1B,WGM12,TCCR1B,WGM13,
		__timer1Compare,TIMSK1,TOIE1,TIFR1,TOV1,ICR1,TIMSK1,ICIE1,TIFR1,ICF1,TCCR1B,ICES1,null,prescale_a),
	MAKE_TIMER(__timer2_data,TCNT2,TCCR2B,7,false,16,mode2WGM_a,
		TCCR2A,WGM20,TCCR2A,WGM21,TCCR2B,WGM22,UNUSED_PORT,0,
		__timer2Compare,TIMSK2,TOIE2,TIFR2,TOV2,UNUSED_PORT,UNUSED_PORT,0,UNUSED_PORT,0,UNUSED_PORT,0,null,prescale_b),
	MAKE_TIMER(__timer3_data,TCNT3,TCCR3B,7,true,16,mode2WGM_b,
		TCCR3A,WGM30,TCCR3A,WGM31,TCCR3B,WGM32,TCCR3B,WGM33,
		__timer3Compare,TIMSK3,TOIE3,TIFR3,TOV3,ICR3,TIMSK3,ICIE3,TIFR3,ICF3,TCCR3B,ICES3,E7,prescale_a),
	MAKE_TIMER(__timer4_data,TCNT4,TCCR4B,7,true,16,mode2WGM_b,
		TCCR4A,WGM40,TCCR4A,WGM41,TCCR4B,WGM42,TCCR4B,WGM43,
		__timer4Compare,TIMSK4,TOIE4,TIFR4,TOV4,ICR4,TIMSK4,ICIE4,TIFR4,ICF4,TCCR4B,ICES4,L0,prescale_a),
	MAKE_TIMER(__timer5_data,TCNT5,TCCR5B,7,true,16,mode2WGM_b,
		TCCR5A,WGM50,TCCR5A,WGM51,TCCR5B,WGM52,TCCR5B,WGM53,
		__timer5Compare,TIMSK5,TOIE5,TIFR5,TOV5,ICR5,TIMSK5,ICIE5,TIFR5,ICF5,TCCR5B,ICES5,L1,prescale_a)
};
const uint8_t NUMBER_OF_TIMERS =  (sizeof(pgm_Timers)/sizeof(Timer));
// ----------- End Timer Definition -------------

